# Generated by Django 4.2.7 on 2023-11-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmListModel',
            new_name='MangaListModel',
        ),
    ]
