# Generated by Django 4.2.7 on 2023-11-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_rename_filmlistmodel_mangalistmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afisha',
            old_name='film',
            new_name='manga',
        ),
        migrations.AlterField(
            model_name='mangalistmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание манги'),
        ),
        migrations.AlterField(
            model_name='mangalistmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Напишите название манги'),
        ),
    ]
