# Generated by Django 4.2.7 on 2023-11-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_mangalistmodel_options_alter_afisha_manga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=20)),
                ('description', models.TextField()),
                ('manga_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_page.mangalistmodel')),
            ],
        ),
    ]
