# Generated by Django 4.2.7 on 2023-11-27 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_reviewmodel_manga_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='manga_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_list_name', to='main_page.mangalistmodel'),
        ),
    ]
